remote_theme: "mmistakes/minimal-mistakes@4.19.3"

minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-archives

permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true

title: "doanhluong.me"
name: "Doanh Luong"
url: "https://kimdoanh89.github.io"
baseurl: "doanhluong.me"

comments:
  provider: "disqus"
  disqus:
    shortname: "doanhluong"

search: true

author:
  name: "Doanh Luong"
  # avatar: "/assets/images/bio-photo.jpg"
  bio: "I am an **amazing** person." # Note: Markdown is allowed
  location: "Somewhere"
  links:
    - label: "Personal Page"
      icon: "fas fa-fw fa-link"
      url: "https://mademistakes.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mmistakes"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kimdoanh89"



category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/